### ISSUE TITLE
Ensure docker-compose.yml will work

### ISSUE THREAD

**Issue by snario** [mapcentia/dockerfiles#5]
I updated the file a bit but it still isn't perfect

The main issues still are
- [ ] No way to handle secrets
- [ ] The nodejs process can take the same address as the apache2 process in gc2core
- [ ] Volumes rely on folders not in this repo, for example `./data`

``` yml
postgis:
    build: ./postgis
    ports:
        - 5432:5432
    environment:
        - GC2_PASSWORD=xxxxxx
elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data
geoserver:
    build: ./geoserver
    ports:
        - "8080:8080"
    links:
        - postgis:postgis
kibana:
    build: kibana/
    volumes:
        - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
        - "5601:5601"
    links:
        - elasticsearch
    environment:
        - NODE_OPTIONS=--max-old-space-size=200
gc2core:
    build: ./gc2core
    ports:
        - "80:80"
        - "443:443"
        - "1339:1339"
    links:
        - postgis:postgis
        - elasticsearch:elasticsearch
        - geoserver:geoserver
    volumes:
        - ./gc2core/conf/gc2:/var/www/geocloud2/app/conf
        - ./gc2core/conf/apache:/etc/apache2/sites-enabled/
        - ./data/apache2/ssl:/etc/apache2/ssl
        # - ./data/fpm:/etc/php5/fpm/
        - ./data/gc2/tmp:/var/www/geocloud2/app/tmp
        - ./data/gc2/mapcache:/var/www/geocloud2/app/wms/mapcache
    environment:
        - GC2_PASSWORD=xxxxxx
mapcache:
    build: ./mapcache
    net: container:gc2core
    volumes:
        - ./data/gc2/mapcache:/var/www/geocloud2/app/wms/mapcache
        - ./data/gc2/tmp:/var/www/geocloud2/app/tmp
```

**Comment by mapcentia** [comment]
```yml
# Create a file called gc2.env with these vars
#
# GC2_PASSWORD=12345
# TIMEZONE=CET
# LOCALE=en_US.UTF-8
#

version: '3'
services:
  postgis:
    #build: ../../postgis/.
    image: mapcentia/postgis
    volumes:
      - postgis_var_www_geocloud2:/var/www/geocloud2
      - postgis_var_lib_postgresql:/var/lib/postgresql
      - postgis_var_log:/var/log
      - postgis_etc_postgresql:/etc/postgresql
      - postgis_etc_pgbouncer:/etc/pgbouncer
    env_file:
      - gc2.env

  gc2core:
    #build: .
    image: mapcentia/gc2core
    privileged: true
    ports:
      - "8080:80"
      #- "443:443"
      #- "1339:1339"
    links:
      - postgis:postgis
    volumes:
      - gc2core_var_www_geocloud2:/var/www/geocloud2
      - gc2core_var_log:/var/log
    env_file:
      - gc2.env

  mapcache:
    #build: ../../mapcache/.
    image: mapcentia/mapcache
    network_mode: service:gc2core
    volumes:
      - gc2core_var_www_geocloud2:/var/www/geocloud2

volumes:
    gc2core_var_www_geocloud2:
    gc2core_var_log:
    postgis_var_log:
    postgis_var_www_geocloud2:
    postgis_etc_postgresql:
    postgis_var_lib_postgresql:
    postgis_etc_pgbouncer:

```
